### ISSUE TITLE
Crash/Freeze when using <curr> in ShopListing

### ISSUE THREAD

**Issue by Sharparam** [fsckyou/BetterShop#1]
When I include the tag "<curr>" in the ShopListing listing message to show currency, the server will crash/freeze when doing /shoplist.

The <curr> tag was placed at the end of the message with nothing after it.

Using version 1.6.2.6

**Comment by jascotty2** [comment]
sorry took so long to get back to you.. forgot to check here :(

cannot reproduce... if you're still having problems, post the relevant line here

**Comment by Sharparam** [comment]
I'm still getting the error using latest (as of April 7, 18:38 (GMT+1)) version of BetterShop.

I get the freeze/crash when the string for shoplisting looks like this:

listing: "&amp;7[&amp;f&lt;item&gt;&amp;7]&amp;2 &lt;l&gt; Buy: &9amp;&lt;buyprice&gt;&amp;2 &lt;curr&gt;.  Sell: &amp;9&lt;sellprice&gt;&amp;2 &lt;curr&gt;."

When it looks like this it all works fine:

listing: "&amp;7[&amp;f&lt;item&gt;&amp;7]&amp;2 &lt;l&gt; Buy: &amp;9&lt;buyprice&gt;&amp;2  Sell: &amp;9&lt;sellprice&gt;"

(edit: fixed the &lt;&gt; being mistaken for html tags)

Server is running at minecraft.f16gaming.com in case you want to take a look.

List of installed plugins:
BetterShop
CraftIRC
Essentials
EssentialsProtect
EssentialsSpawn
EssentialsGroupManager (with GroupBridge)
HeroChat
HeroicDeath
iConomy
LevelCraft
NoCheat
Uptime
Vanish
WorldEdit
WorldGuard

I'll see if i can put up a list of the version for every plugin but for most of them it's the latest available. (at least as of April 6).

**Comment by jascotty2** [comment]
thanks for this error report! :)

as it turns out, there was a serious bug in the align tags logic (it thought <curr> was trying to center-align, but didn't know how)
the fix will be included with the next release
(can't release yet, unstable testing)
